Program to Demonstrate Thread Priority in Java

Aim:
To write and execute a Java program to create multiple threads and assign different priority levels to them using the setPriority() method.

Algorithm:
Create three thread classes A, B, and C.
Override the run() method in each class.
Create objects for the three threads.
Assign priorities 3, 5, and 7 to threads A, B, and C.
Start all three threads using the start() method.
Execute the statements inside each run() method.
Display the messages generated by the threads.

Program:
class A extends Thread
{
    public void run()
    {
        System.out.println("Thread A started");

        for(int i = 1; i <= 4; i++)
        {
            System.out.println("From thread A i = " + i);
        }

        System.out.println("Exit from A");
    }
}

class B extends Thread
{
    public void run()
    {
        System.out.println("Thread B started");

        for(int j = 1; j <= 4; j++)
        {
            System.out.println("From thread B j = " + j);
        }

        System.out.println("Exit from B");
    }
}

class C extends Thread
{
    public void run()
    {
        System.out.println("Thread C started");

        for(int j = 1; j <= 4; j++)
        {
            System.out.println("Thread C = " + j);
        }

        System.out.println("Exit from C");
    }
}

class ThreadPriority
{
    public static void main(String args[])
    {
        A a = new A();
        B b = new B();
        C c = new C();

        System.out.println("Start thread A");
        System.out.println("Start thread B");
        System.out.println("Start thread C");

        a.setPriority(3);
        b.setPriority(5);
        c.setPriority(7);

        a.start();
        b.start();
        c.start();

        System.out.println("End of main thread");
    }
}

Output:

Start thread A
Start thread B
Start thread C
End of main thread
Thread C started
From thread B j = 1
Thread C = 1
From thread A i = 1
From thread B j = 2
Thread C = 2
From thread A i = 2
From thread B j = 3
Thread C = 3
From thread A i = 3
From thread B j = 4
Thread C = 4
From thread A i = 4
Thread C = 5
Exit from A
Exit from B
Exit from C

Result:
Thus, the program successfully demonstrates the creation of multiple threads and assigning different priorities using setPriority() in Java
